site_name: enigma-engines
repo_url: https://github.com/shankha06/enigma-engines
site_url: https://shankha06.github.io/enigma-engines
site_description: This is a template repository for Python projects that use uv for their dependency management.
site_author: Shankhadeep Roy
edit_uri: edit/main/docs/
repo_name: shankha06/enigma-engines
copyright: Maintained by <a href="https://shankha06.com">shankha06</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["enigma_engines"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shankha06/enigma-engines
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/enigma-engines

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
